### ISSUE TITLE
Packages based on new Anaconda compilers

### ISSUE THREAD

**Issue by Zaharid** [NLeSC/root-conda-recipes#33]
It looks like the new compiler tools:

https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html

may significantly simplify  the recipes here and mitigate some of the problems.

**Comment by egpbos** [comment]
The NLeSC ROOT Conda package is no longer maintained and does not work properly with current Conda, modern Python, or modern ROOT. Use conda-forge ROOT instead:

### Installing in a new environment:

```bash
conda create -n myrootenv python=3.7 root -c conda-forge
conda activate myrootenv
conda config --env --add channels conda-forge
```

From then on, use `conda activate myrootenv` to get in and `conda deactivate` to get out of the env. You should have a recent version of conda.

or

### Installing in the current environment:

```bash
conda config --env --add channels conda-forge 
conda install root
```

Unlike the NLeSC package, this can even be the base environment if you really want to do that (it is not ideal, since it will be rather invasive, adding things like conda's compiler packages that are needed to compile with ROOT and Conda).

Conda-forge ROOT provides ROOT 6.16.00+, and supports Python 3.7, 3.6, and 2.7 on macOS and Linux. It is being tested by the ROOT team, and is automatically build by the conda-forge infrastructure. All default features and a huge number of optional features are turned on, and you can use it anywhere you would use ROOT, JupyROOT, or PyROOT.
