### ISSUE TITLE
ROOT 6.10 / 6.12 build

### ISSUE THREAD

**Issue by adsherman** [NLeSC/root-conda-recipes#35]
Will there be a new build for a more recent version of ROOT? As far as I can tell 6.04 is the last stable release, and there is no gcc-6 build (still 4.8). Thanks!

**Comment by egpbos** [comment]
The NLeSC ROOT Conda package is no longer maintained and does not work properly with current Conda, modern Python, or modern ROOT. Use conda-forge ROOT instead:

### Installing in a new environment:

```bash
conda create -n myrootenv python=3.7 root -c conda-forge
conda activate myrootenv
conda config --env --add channels conda-forge
```

From then on, use `conda activate myrootenv` to get in and `conda deactivate` to get out of the env. You should have a recent version of conda.

or

### Installing in the current environment:

```bash
conda config --env --add channels conda-forge 
conda install root
```

Unlike the NLeSC package, this can even be the base environment if you really want to do that (it is not ideal, since it will be rather invasive, adding things like conda's compiler packages that are needed to compile with ROOT and Conda).

Conda-forge ROOT provides ROOT 6.16.00+, and supports Python 3.7, 3.6, and 2.7 on macOS and Linux. It is being tested by the ROOT team, and is automatically build by the conda-forge infrastructure. All default features and a huge number of optional features are turned on, and you can use it anywhere you would use ROOT, JupyROOT, or PyROOT.

**Comment by adsherman** [comment]
Hi @egpbos,

This is great news! Unfortunately I tried these commands from a fresh shell and I ran into problems, maybe you are familiar with them?:

```
-bash-4.1$ source activate myrootenv
Activate: ROOT has been sourced. Environment settings are ready.
ROOTSYS=/home/graduate/adsherma/miniconda2/envs/myrootenv
(myrootenv) -bash-4.1$ root
root: /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/././libicuuc.so.58)
root: /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/././libicuuc.so.58)
(myrootenv) -bash-4.1$
```

I have not installed any other packages into this env yet, and I followed your instructions 
```
conda create -n myrootenv python=3.7 root -c conda-forge
conda activate myrootenv
conda config --env --add channels conda-forge
```
with the exception that I needed to use ```source activate myrootenv``` since ```conda activate myrootenv``` flashed this error:

```
-bash-4.1$ conda activate myrootenv

CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?


-bash-4.1$
```

I previously always used ```source activate <env>```; do I have an old version of miniconda that is perhaps incompatible?

Thanks!
-Alex

**Comment by egpbos** [comment]
You do seem to have an older miniconda, indeed. I'm not sure whether this causes your problems, but please give it a try with the newest miniconda.

**Comment by adsherman** [comment]
Hi @egpbos,

Sorry it took awhile before I got back to this. I installed the newest linux miniconda and tried again, and still got this error:

```
root: /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/././libicuuc.so.58)
root: /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/graduate/adsherma/miniconda2/envs/myrootenv/bin/../lib/././libicuuc.so.58)
```

If it matters I used python 2.7 not 3.7, that was a typo in my previous post.

**Comment by egpbos** [comment]
Could you maybe make an issue on the [conda-forge recipe page](https://github.com/conda-forge/root-feedstock/)? You can link to this issue to avoid having to repeat yourself.

**Comment by adsherman** [comment]
The solution has been found! The old NLeSC channel was still in .condarc and was being used at higher priority than some of the new packages. Removing the line from .condarc and reinstalling solved the problem.
