### ISSUE TITLE
Rebuild root6 with --enable-minuit2 ?

### ISSUE THREAD

**Issue by fdesse** [NLeSC/root-conda-recipes#41]
Dear all,

I have a script using `Minuit2/Minuit2Minimizer.h`. It seems that by default, the root6 built when doing
```
conda install root
```
does not include minuit2. Indeed:
```
$ root-config --features
$ asimage astiff builtin_afterimage builtin_ftgl builtin_freetype builtin_glew builtin_pcre builtin_zlib builtin_lzma builtin_llvm cxx11 cling exceptions explicitlink fftw3 fortran genvector mathmore memstat pch python roofit rpath shadowpw shared sqlite ssl thread tmva vdt xft xml x11
```
 I believe I should rebuild my anaconda root with the option `--enable-minuit2`. Is there a way to do this within anaconda ?

By searching in the doc provided on this GitHub, I found this:
```
CONDA_PY=3.4 conda build root6
```
But how can I specify the option to unable minuit2 ? Also, it seems I have to specify the path to the build directory of root. Any idea where this can be (I have a vanilla anaconda/miniconda3, I did not make any funny changes)

Many thanks !
Fabrice

**Comment by egpbos** [comment]
Thanks for posting this issue. Minuit2 should definitely be in the build. We are currently redesigning the build process and will take this into account in the new builds that will come out of that.

**Comment by fdesse** [comment]
Thanks for your reply ! Indeed in the long term, I think its a good idea to add Minuit2.
On the short term, is there no way to rebuild root "by hand"  in the virtual env ? What I mean by that is doing something like:
1) Install root in the virtual env like usual with `conda install root`
2) somehow telling anaconda "well, I'm not super happy with this build of root, I'd like to rebuild it with the following options"

Is step 2 not conceivable ? I guess that, independently of Minuit2, it can happen from time to time that people would like to rebuild root in order to add something they need, no ?

**Comment by egpbos** [comment]
AFAIK, the ROOT source is not distributed with the Conda package, so rebuilding from the package would not be possible.

**Comment by fdesse** [comment]
OK. Too bad ... thx for your help anyway.
I'll look forward for the new builds then ! :)

**Comment by egpbos** [comment]
The NLeSC ROOT Conda package is no longer maintained and does not work properly with current Conda, modern Python, or modern ROOT. Use conda-forge ROOT instead:

### Installing in a new environment:

```bash
conda create -n myrootenv python=3.7 root -c conda-forge
conda activate myrootenv
conda config --env --add channels conda-forge
```

From then on, use `conda activate myrootenv` to get in and `conda deactivate` to get out of the env. You should have a recent version of conda.

or

### Installing in the current environment:

```bash
conda config --env --add channels conda-forge 
conda install root
```

Unlike the NLeSC package, this can even be the base environment if you really want to do that (it is not ideal, since it will be rather invasive, adding things like conda's compiler packages that are needed to compile with ROOT and Conda).

Conda-forge ROOT provides ROOT 6.16.00+, and supports Python 3.7, 3.6, and 2.7 on macOS and Linux. It is being tested by the ROOT team, and is automatically build by the conda-forge infrastructure. All default features and a huge number of optional features are turned on, and you can use it anywhere you would use ROOT, JupyROOT, or PyROOT.
