### ISSUE TITLE
cling error missing libraries

### ISSUE THREAD

**Issue by sidebo** [NLeSC/root-conda-recipes#44]
After what appears to be a successful install (`sudo conda install root`) on an slc6 machine, I cannot run root. I get the following:

```
[psidebo@gluino ~]$ root
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
    echo | LC_ALL=C c++  -pipe -m64 -Wall -W -Woverloaded-virtual -fsigned-char -fPIC -pthread -std=c++11 -Wno-deprecated-declarations -Wno-comment -Wno-unused-parameter -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-missing-field-initializers -fPIC -fvisibility-inlines-hidden -std=c++11 -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -Wcast-qual -fno-strict-aliasing -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-unused-local-typedefs -O2 -DNDEBUG -xc++ -E -v - 2>&1 >/dev/null | awk '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ print }}' | grep -E "(c|g)\+\+"
results in
with exit code 256
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^
input_line_3:38:10: fatal error: 'string' file not found
#include <string>
         ^
input_line_8:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
```
Any help would be appreciated.

**Comment by egpbos** [comment]
Usually, `conda` is run as a regular user, i.e. without `sudo`. Is there any specific reason why you install using `sudo`?

Installing in the default `conda` environment is also problematic. Could you try installing in a new environment? For instance, install + activate environment + run like this:
```sh
conda create -n root root -c nlesc
source activate root
root
```

**Comment by egpbos** [comment]
The NLeSC ROOT Conda package is no longer maintained and does not work properly with current Conda, modern Python, or modern ROOT. Use conda-forge ROOT instead:

### Installing in a new environment:

```bash
conda create -n myrootenv python=3.7 root -c conda-forge
conda activate myrootenv
conda config --env --add channels conda-forge
```

From then on, use `conda activate myrootenv` to get in and `conda deactivate` to get out of the env. You should have a recent version of conda.

or

### Installing in the current environment:

```bash
conda config --env --add channels conda-forge 
conda install root
```

Unlike the NLeSC package, this can even be the base environment if you really want to do that (it is not ideal, since it will be rather invasive, adding things like conda's compiler packages that are needed to compile with ROOT and Conda).

Conda-forge ROOT provides ROOT 6.16.00+, and supports Python 3.7, 3.6, and 2.7 on macOS and Linux. It is being tested by the ROOT team, and is automatically build by the conda-forge infrastructure. All default features and a huge number of optional features are turned on, and you can use it anywhere you would use ROOT, JupyROOT, or PyROOT.
